.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. digibyte_qt test_digibyte_qt
clean: FORCE
	$(MAKE) -C .. digibyte_qt_clean test_digibyte_qt_clean
check: FORCE
	$(MAKE) -C .. test_digibyte_qt_check
digibyte-qt digibyte-qt.exe: FORCE
	 $(MAKE) -C .. digibyte_qt
apk: FORCE
	$(MAKE) -C .. digibyte_qt_apk
